name: build-realm-cpp
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version tag"
        required: false
        default: "2.2.0"
      rc:
        description: "rc"
        required: false
        default: ""
      target:
        description: "build target"
        required: true
        default: "all"
        type: choice
        options:
          - linux-clang
          - msvc
          - all

permissions:
  contents: write

jobs:
  build-linux-clang:
    if: inputs.target == 'linux-clang' || inputs.target == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get update -y && sudo apt-get install -y clang cmake ninja-build
      - name: build
        run: |
          bash ./scripts/realm-cpp.sh --version=${{ inputs.version }} --build-variant=linux-clang
          bash ./scripts/realm-cpp.sh --version=${{ inputs.version }} --build-variant=linux-clang-fpic
      - uses: actions/upload-artifact@v4
        with:
          name: realm-linux-clang
          path: packages/*.tar.gz

  build-msvc:
    if: inputs.target == 'msvc' || inputs.target == 'all'
    runs-on: windows-latest
    steps:
      - name: fix line endings
        run: git config --global core.autocrlf input
        shell: pwsh
      - uses: actions/checkout@v4
      - name: build
        shell: pwsh
        run: .\scripts\realm-cpp.ps1 -Toolchain msvc -Version ${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: realm-msvc
          path: packages/*.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: [build-linux-clang, build-msvc]
    if: always() && !failure() && !cancelled()
    steps:
      - name: download linux-clang artifact
        if: needs.build-linux-clang.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: realm-linux-clang
          path: dist
      - name: download msvc artifact
        if: needs.build-msvc.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: realm-msvc
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: realm-cpp-${{ inputs.version }}${{ inputs.rc != '' && format('-{0}', inputs.rc) || '' }}
          name: realm-cpp-${{ inputs.version }}${{ inputs.rc != '' && format('-{0}', inputs.rc) || '' }}
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
