name: build realm-cpp-fork

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version tag"
        required: false
        default: "2.2.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: fix line endings
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: git config --global core.autocrlf input

      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: setup msys2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-ninja

      - name: setup linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build

      - name: build (linux)
        if: matrix.os == 'ubuntu-latest'
        run: bash ./scripts/realm-cpp.sh --platform=linux --version=${{ inputs.version }}

      - name: build (windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: bash ./scripts/realm-cpp.sh --platform=windows --version=${{ inputs.version }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./*.tar.gz

      - name: upload release asset
        uses: softprops/action-gh-release@v3
        with:
          tag_name: realm-cpp-${{ inputs.version }}
          name: build
          files: |
            - *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}